### PR TITLE
Fix of https://github.com/hase-project/hase/issues/41

### PR DESCRIPTION
**Pull request by Airtnp**
Need to update archinfo module to latest version (If you encounter get_base_register, then it's this problem)

### CODE REVIEW

**Comment by Mic92** [comment]
Is archinfo 8.18.10.25 new enough?

**Comment by Mic92** [comment]
I rebased our branch instead: https://github.com/hase-project/angr/commits/angr-10-12-2018

**Comment by Airtnp** [comment]
No exactly the last commit version of archinfo

**Comment by Airtnp** [comment]
Shall I pull a new request to new branch?

**Comment by Mic92** [comment]
The fix is already included.

**Pull request closed without merging**
